run:
  timeout: 3m

linters:
  enable-all: true
  disable:
    - exportloopref
    - wsl
    - nolintlint
    - varnamelen
    - depguard

linters-settings:
  wrapcheck:
    ignoreSigs:
      - werr.Wrap(
      - werr.Wrapf(
      - werr.Unwrap(

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - wrapcheck
        - err113
        - funlen
